import { AssetCategory, AssetDefinition, CategoryDefinition } from '../types/assets';

export const CATEGORIES: Record<AssetCategory, CategoryDefinition> = {
  foh_pa: {
    id: 'foh_pa',
    name: 'FOH & PA System',
    color: '#3b82f6', // Indigo/Blue
    textColor: 'text-blue-400',
    borderColor: 'border-blue-500/40',
    accentBg: 'bg-blue-500/15',
  },
  monitoring: {
    id: 'monitoring',
    name: 'Monitoring',
    color: '#f97316', // Orange
    textColor: 'text-orange-400',
    borderColor: 'border-orange-500/40',
    accentBg: 'bg-orange-500/15',
  },
  backline: {
    id: 'backline',
    name: 'Backline & Instruments',
    color: '#10b981', // Emerald Green
    textColor: 'text-emerald-400',
    borderColor: 'border-emerald-500/40',
    accentBg: 'bg-emerald-500/15',
  },
  infrastructure: {
    id: 'infrastructure',
    name: 'Infrastructure & Power',
    color: '#f59e0b', // Amber
    textColor: 'text-amber-400',
    borderColor: 'border-amber-500/40',
    accentBg: 'bg-amber-500/15',
  },
};

export const ASSET_CATALOG: AssetDefinition[] = [
  // FOH & PA
  {
    id: 'main_pa_speaker',
    name: 'Main PA Speaker',
    category: 'foh_pa',
    defaultLabel: 'Main PA',
    width: 44,
    height: 44,
    realWidthMeters: 0.6,
    realHeightMeters: 0.6,
    iconName: 'Speaker',
    description: 'Front of House line array or point source top cab',
    colorAccent: '#3b82f6',
    badgeText: 'PA',
  },
  {
    id: 'subwoofer',
    name: 'Subwoofer',
    category: 'foh_pa',
    defaultLabel: 'Sub Array',
    width: 52,
    height: 46,
    realWidthMeters: 0.8,
    realHeightMeters: 0.7,
    iconName: 'Disc',
    description: 'Ground-stacked or flown low-frequency reinforcement',
    colorAccent: '#3b82f6',
    badgeText: 'SUB',
  },
  {
    id: 'foh_console',
    name: 'FOH Mixing Console',
    category: 'foh_pa',
    defaultLabel: 'FOH Desk',
    width: 80,
    height: 52,
    realWidthMeters: 1.2,
    realHeightMeters: 0.8,
    iconName: 'Sliders',
    description: 'Front of House mixing desk (auto-connects multicore to Stage Box)',
    colorAccent: '#3b82f6',
    badgeText: 'FOH',
  },

  // Monitoring
  {
    id: 'foldback_wedge',
    name: 'Foldback Wedge',
    category: 'monitoring',
    defaultLabel: 'Mix 1 Wedge',
    width: 46,
    height: 38,
    realWidthMeters: 0.6,
    realHeightMeters: 0.5,
    iconName: 'Volume2',
    description: 'Standard angled profile floor monitor wedge',
    colorAccent: '#f97316',
    badgeText: 'MON',
  },
  {
    id: 'side_fill',
    name: 'Drum / Side Fill',
    category: 'monitoring',
    defaultLabel: 'Side Fill',
    width: 44,
    height: 54,
    realWidthMeters: 0.6,
    realHeightMeters: 0.8,
    iconName: 'Radio',
    description: 'High-output stage fill or dedicated drum monitor stack',
    colorAccent: '#f97316',
    badgeText: 'FILL',
  },

  // Backline & Instruments
  {
    id: 'drum_kit',
    name: 'Drum Kit',
    category: 'backline',
    defaultLabel: 'Drum Kit',
    width: 90,
    height: 90,
    realWidthMeters: 1.8,
    realHeightMeters: 1.8,
    iconName: 'CircleDot',
    description: 'Standard top-down acoustic drum kit footprint with cymbals',
    colorAccent: '#10b981',
    badgeText: 'DRUMS',
  },
  {
    id: 'amp_cab',
    name: 'Guitar / Bass Amp Cab',
    category: 'backline',
    defaultLabel: 'Guitar Amp',
    width: 48,
    height: 36,
    realWidthMeters: 0.7,
    realHeightMeters: 0.5,
    iconName: 'Box',
    description: 'Backline amplifier combo or 4x12/8x10 speaker cabinet',
    colorAccent: '#10b981',
    badgeText: 'AMP',
  },
  {
    id: 'keyboard_rig',
    name: 'Keyboard / Synth Rig',
    category: 'backline',
    defaultLabel: 'Keys Rig',
    width: 68,
    height: 42,
    realWidthMeters: 1.2,
    realHeightMeters: 0.6,
    iconName: 'Grid',
    description: 'Single/dual tier synthesizer, workstation or digital piano',
    colorAccent: '#10b981',
    badgeText: 'KEYS',
  },
  {
    id: 'pedalboard',
    name: 'Pedalboard / Floor FX',
    category: 'backline',
    defaultLabel: 'Pedalboard',
    width: 40,
    height: 26,
    realWidthMeters: 0.6,
    realHeightMeters: 0.4,
    iconName: 'Layers',
    description: 'Musician pedalboard or vocal multieffects stompbox',
    colorAccent: '#10b981',
    badgeText: 'FX',
  },

  // Infrastructure
  {
    id: 'stage_box',
    name: 'Stage Box (I/O Drop)',
    category: 'infrastructure',
    defaultLabel: 'Stage Box',
    width: 44,
    height: 34,
    realWidthMeters: 0.6,
    realHeightMeters: 0.4,
    iconName: 'Cpu',
    description: 'Digital snake stage box / analog mult / sub-snake drop',
    colorAccent: '#f59e0b',
    badgeText: 'I/O',
  },
  {
    id: 'power_drop',
    name: '13A Mains Power Drop',
    category: 'infrastructure',
    defaultLabel: '',
    width: 26,
    height: 26,
    realWidthMeters: 0.35,
    realHeightMeters: 0.35,
    iconName: 'Zap',
    description: 'Clean stage mains power drop / socket symbol',
    colorAccent: '#f59e0b',
    badgeText: 'PWR',
  },
];

export const ASSET_MAP = new Map<string, AssetDefinition>(
  ASSET_CATALOG.map((a) => [a.id, a])
);
