import { VenueTemplate } from '../types/stage';

export const VENUE_TEMPLATES: VenueTemplate[] = [
  {
    id: 'small_club_01',
    name: 'Small Stage (6m × 4m)',
    description: 'End-on stage layout suited for pubs, clubs, and intimate live rooms.',
    capacity: '100–250',
    stageDimensions: '6m × 4m (End-on)',
    stageWidthMeters: 6,
    stageHeightMeters: 4,
    canvasWidth: 900,
    canvasHeight: 960,
    pixelsPerMeter: 60, // 6m = 360px, 4m = 240px
    zones: [
      {
        id: 'stage_zone',
        name: 'RAISED STAGE (6m × 4m)',
        x: 170,
        y: 60,
        width: 560,
        height: 340,
        fillColor: 'rgba(30, 41, 59, 0.45)',
        strokeColor: '#38bdf8',
        labelColor: '#38bdf8',
        dashed: false,
      },
      {
        id: 'audience_zone',
        name: 'AUDIENCE / STANDING FLOOR',
        x: 170,
        y: 430,
        width: 560,
        height: 340,
        fillColor: 'rgba(15, 23, 42, 0.35)',
        strokeColor: '#64748b',
        labelColor: '#94a3b8',
        dashed: true,
      },
      {
        id: 'foh_zone',
        name: 'FOH MIX POSITION',
        x: 330,
        y: 800,
        width: 240,
        height: 110,
        fillColor: 'rgba(59, 130, 246, 0.08)',
        strokeColor: '#3b82f6',
        labelColor: '#60a5fa',
        dashed: true,
      },
    ],
  },
  {
    id: 'mid_theatre_01',
    name: 'Mid-Sized Stage (12m × 8m)',
    description: 'Proscenium / thrust stage layout with seated stalls & central sound booth.',
    capacity: '500–1000',
    stageDimensions: '12m × 8m (Proscenium)',
    stageWidthMeters: 12,
    stageHeightMeters: 8,
    canvasWidth: 1100,
    canvasHeight: 1150,
    pixelsPerMeter: 50,
    zones: [
      {
        id: 'stage_zone',
        name: 'PROSCENIUM STAGE (12m × 8m)',
        x: 150,
        y: 60,
        width: 800,
        height: 480,
        fillColor: 'rgba(30, 41, 59, 0.45)',
        strokeColor: '#38bdf8',
        labelColor: '#38bdf8',
        dashed: false,
      },
      {
        id: 'audience_zone',
        name: 'SEATED STALLS / AUDIENCE',
        x: 150,
        y: 570,
        width: 800,
        height: 400,
        fillColor: 'rgba(15, 23, 42, 0.35)',
        strokeColor: '#64748b',
        labelColor: '#94a3b8',
        dashed: true,
      },
      {
        id: 'foh_zone',
        name: 'DEDICATED CENTRAL FOH POSITION',
        x: 400,
        y: 1000,
        width: 300,
        height: 110,
        fillColor: 'rgba(59, 130, 246, 0.08)',
        strokeColor: '#3b82f6',
        labelColor: '#60a5fa',
        dashed: true,
      },
    ],
  },
];

export const TEMPLATE_MAP = new Map<string, VenueTemplate>(
  VENUE_TEMPLATES.map((t) => [t.id, t])
);
